version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/ # persist data even if container shuts down
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080